dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
env:
  - CODACY_PROJECT_TOKEN=44bfe82789bc4961be27f5532cab04bb
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
script:
  - cd decide
  - coverage run --branch --source=. ./manage.py test base --keepdb
  - coverage xml
  - python-codacy-coverage -r coverage.xml
notifications:
  email:
    recipients:
      - dansanbal@alum.us.es
    on_success: never 
    on_failure: always
